---
- name: 允许Node加入集群
  ignore_errors: yes
  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')

- name: 拷贝YAML文件到Master
  copy: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "*.yaml"

- name: 部署Flannel,Dashboard,CoreDNS,Ingress,Kuboard
  ignore_errors: yes
  shell: |
         cd {{ tmp_dir }}
         for yaml in $(ls *.yaml);do kubectl apply -f $yaml;done

- name: 替换Dashboard证书
  shell: |
         kubectl delete secret kubernetes-dashboard-certs -n kubernetes-dashboard |true
         kubectl create secret generic kubernetes-dashboard-certs \
         --from-file={{ k8s_work_dir }}/ssl/server-key.pem --from-file={{ k8s_work_dir }}/ssl/server.pem -n kubernetes-dashboard
         kubectl apply -f {{ tmp_dir }}/kubernetes-dashboard.yaml

- name: 查看Pod状态
  shell: kubectl get all --all-namespaces
  register: getall
- debug: var=getall.stdout_lines


- name: 获取Kuboard管理员令牌kubectl -n kube-system get secret $(kubectl get secret -n kube-system | grep kuboard-user | awk '{print $1}') -o go-template='{{.data.token}}' | base64 -d
  ignore_errors: yes
  shell: |
         web='http://NodeIP:32567/#/dashboard?k8sToken='
         token=$(kubectl -n kube-system get secret $(kubectl get secret -n kube-system | grep kuboard-user | awk '{print $1}') -o go-template='{{.data.token}}' | base64 -d)
         echo "访问地址--->$web"
         echo "管理员令牌内容--->$token"
  register: ui
- name: Kuboard管理员登录信息
  debug: var=ui.stdout_lines